[[how-to-write-promise]]
== Promiseの書き方

Promiseの基本的な書き方について解説します。

=== promiseオブジェクトの作成

promiseオブジェクトを作る流れは以下のようになっています。

. `new Promise(fn)` の返り値がpromiseオブジェクト
. `fn` には非同期等の何らかの処理を書く
    * 処理結果が正常なら、`resolve(結果の値)` を呼ぶ
    * 処理結果がエラーなら、`reject(Errorオブジェクト)` を呼ぶ


この流れに沿っているものを実際に書いてみましょう。

非同期処理であるXMLHttpRequest(XHR)を使いデータを取得するものをPromiseで書いていきます。

==== XHRのpromiseオブジェクトを作る

まずは、XHRをPromiseを使って包んだような `fetchURL` という関数を作ります。

[role="executable"]
[[xhr-promise.js]]
.xhr-promise.js
[source,javascript]
----
include::embed/embed-xhr-promise.js[]
// 実行例
const URL = "https://httpbin.org/get";
fetchURL(URL).then(function onFulfilled(value){
    console.log(value);
}).catch(function onRejected(error){
    console.error(error);
});
----

この `fetchURL` では、
XHRでの取得結果のステータスコードが200以上300未満の場合は `resolve` - つまり取得に成功、
それ以外はエラーであるとして `reject` しています。

`resolve(req.responseText)` ではレスポンスの内容を引数に入れています。
resolveの引数に入れる値には特に決まりはありませんが、コールバックと同様に次の処理へ渡したい値を入れるといいでしょう。
(この値は `then` メソッドで受け取ることができます)

Node.jsをやっている人は、コールバックを書く時に `callback(error, response)` と第一引数にエラーオブジェクトを
入れることがよくあると思いますが、Promiseでは役割がresolve/rejectで分担されているので、
resolveにはresponseの値のみをいれるだけで問題ありません。


次に、`reject` の方を見ていきましょう。

XHRで `onerror` のイベントが呼ばれた場合はもちろんエラーなので `reject` を呼びます。
ここで `reject` に渡している値に注目してみてください。

エラーの場合は `reject(new Error(req.statusText));` というように、Errorオブジェクトを作成して渡していることが分かると思います。
`reject` に渡す値に制限はありませんが、一般的にErrorオブジェクト(またはErrorオブジェクトを継承したもの)を渡すことになっています。

`reject` に渡す値は、rejectする理由を書いたErrorオブジェクトとなっています。
今回は、ステータスコードが2xx以外であるならrejectするとしていたため、`reject` にはstatusTextを入れています。
(この値は `then` メソッドの第二引数 or `catch` メソッドで受け取ることができます)

=== promiseオブジェクトに処理を書く

先ほどの作成したpromiseオブジェクトを返す関数を実際に使ってみましょう。

[source,javascript]
fetchURL("https://httpbin.org/get"); // => promiseオブジェクトが返ってくる

<<promises-overview,Promises Overview>> でも簡単に紹介したようにpromiseオブジェクトは幾つかインスタンスメソッドを持っており、
これを使いpromiseオブジェクトの状態に応じて一度だけ呼ばれるコールバックとなる関数を登録します。

promiseオブジェクトに登録する処理は以下の2種類が主となります。

* promiseオブジェクトが **resolve** された時の処理(onFulfilled)
* promiseオブジェクトが **reject** された時の処理(onRejected)

[[promise-value-flow]]
.promise value flow
image::img/promise-onFulfilled_onRejected.png[promise-resolve-flow]

まずは、`fetchURL` で通信が成功して値が取得できた場合の処理を書いてみましょう。

この場合の _通信が成功した_ というのは、
resolveされたことにより _promiseオブジェクトがFulFilledの状態になった_ 時ということですね。

**resolve**された時の処理は、 <<promise.then,`.then`>> メソッドに呼びたい関数を渡すことで行えます。

[source,javascript]
----
const URL = "https://httpbin.org/get";
fetchURL(URL).then(function onFulfilled(value){ // <1>
    console.log(value);
});
----
<1> 分かりやすくするため関数に `onFulfilled` という名前を付けています

<<xhr-promise.js,fetchURL関数>> 内で `resolve(req.responseText);` によってpromiseオブジェクトが解決されると、
値と共に `onFulfilled` 関数が呼ばれます。

このままでは通信エラーが起きた場合などに何も処理がされないため、
今度は、`fetchURL` で何らかの問題があってエラーが起きた場合の処理を書いてみましょう。

この場合の _エラーが起きた_ というのは、
rejectされたことより _promiseオブジェクトがRejectedの状態になった_ 時ということですね。

**reject**された時の処理は、<<promise.then,`.then` の第二引数>> または <<promise.catch,`.catch`>> メソッドに呼びたい関数を渡すことで行えます。

先ほどのソースにrejectされた場合の処理を追加してみましょう。

[source,javascript]
----
const URL = "https://httpbin.org/status/500"; // <1>
fetchURL(URL).then(function onFulfilled(value){
    console.log(value);
}).catch(function onRejected(error){ // <2>
    console.error(error);
});
----
<1> サーバはステータスコード500のレスポンスを返す
<2> 分かりやすくするため関数 `onRejected` という名前を付けています


`fetchURL` の処理中に何らかの理由で例外が起きた場合、または明示的にrejectされた場合に、
その理由(Errorオブジェクト)と共に <<promise.catch,`.catch`>> の処理が呼ばれます。

<<promise.catch,`.catch`>>は `promise.then(undefined, onRejected)` のエイリアスであるため、
同様の処理は以下のように書くこともできます。

[[catch-as-alias]]
[source,javascript]
----
fetchURL(URL).then(onFulfilled, onRejected);// <1>
----
<1> onFulfilled, onRejected それぞれは先ほどと同じ関数

基本的には、<<promise.catch,`.catch`>>を使いresolveとrejectそれぞれを別々に処理した方がよいと考えられますが、
両者の違いについては <<then-or-catch,then or catch?>> で紹介します。

==== まとめ

この章では以下のことについて簡単に紹介しました。

* `new Promise` を使ったpromiseオブジェクトの作成
* <<promise.then,`.then`>> や <<promise.catch,`.catch`>> を使ったpromiseオブジェクトの処理

Promiseの基本的な書き方について学びました。
他の多くの処理はこれを発展させたり、用意された静的メソッドを利用したものになります。

ここでは、同様のことはコールバック関数を渡す形でもできるのに対してPromiseで書くメリットについては触れていませんでした。
次の章では、Promiseのメリットであるエラーハンドリングの仕組みをコールバックベースの実装と比較しながら見ていきたいと思います。
