[[ch2-promise-finally]]
== Promise#finally

ECMAScript 2018からpromise chainの最後に処理を実行する `Promise#finally` メソッド追加されました。

`Promise#finally` メソッドは成功時、失敗時どちらの場合でも呼び出すコールバック関数を登録できます。
`try...catch...finally` 構文の `finally` 節と同様の役割をもつメソッドです。

次のコードのように、 `Promise#finally` メソッドで登録したコールバック関数は、promiseオブジェクトが *resolve*(成功) / *reject*(失敗) どちらの場合でも呼ばれます。

[role="executable"]
[source,javascript]
.finallyのコード例
----
Promise.resolve("成功").finally(() => {
    console.log("成功時に実行される");
});
Promise.reject(new Error("失敗")).finally(() => {
    console.log("失敗時に実行される");
});
----

`finally` メソッドのコールバック関数は引数を受け取らず、どのような値を返してもpromise chainには影響を与えません。
また、 `finally` メソッドは新しいpromiseオブジェクトを返し、新しいpromiseオブジェクトは呼び出し元のpromiseオブジェクトの状態をそのまま引き継ぎます。

[role="executable"]
[source,javascript]
.finallyとpromise chain
----
function onFinally() {
    // 成功、失敗どちらでも実行したい処理
}

// `Promise#finally` は新しいpromiseオブジェクトを返す
Promise.resolve(42)
    .finally(onFinally)
    .then((value) => {
        // 呼び出し元のpromiseオブジェクトの状態をそのまま引き継ぐ
        // 呼び出し元のpromiseオブジェクトは `42` で resolveされている
        console.log(value); // 42
    });
----

`Promise#finally` メソッドと同等の表現を `Promise#then` メソッドで書くと次のように書けます。

[source,javascript]
.finallyをthenで表現
----
function onFinally() {
    // 成功、失敗どちらでも実行したい処理
}

// Promise#finally(onFinally) と同等の表現
promise.then((result) => {
    onFinally();
    return result;
}, (error) => {
    onFinally();
    throw error;
});
----

`Promise#finally` メソッドを使うことで、promise chainで必ず実行したい処理を簡単に書けるようになっています。

次のコードでは、リソースを取得中かどうかを判定するためのフラグを `isLoading` という変数で管理しています。
`Promise#finally` メソッドを使い成功失敗どちらにもかかわらず、取得が終わったら `isLoading` は `false` にしています。

[role="executable"]
[source,javascript]
.finallyのユースケース
----
// リソースを取得中かどうかのフラグ
let isLoading = false;
function fetchResource(URL) {
    // リソース取得中フラグをONに
    isLoading = true;
    return new Promise((resolve, reject) => {
        const req = new XMLHttpRequest();
        req.open("GET", URL, true);
        req.onload = function() {
            if (200 <= req.status && req.status < 300) {
                resolve(req.responseText);
            } else {
                reject(new Error(req.statusText));
            }
        };
        req.onerror = function() {
            reject(new Error(req.statusText));
        };
        req.send();
    }).finally(() => {
        // リソース取得に成功/失敗どちらの場合も取得中フラグをOFFに
        isLoading = false;
    });
}

console.log("リソースロード開始", isLoading);
fetchResource("https://httpbin.org/get").then((value) => {
    console.log("リソース取得に成功", isLoading);
    console.log(value);
}).catch((error) => {
    console.log("リソース取得に失敗", isLoading);
    console.error(error);
});
console.log("リソースロード中", isLoading);
----

`then` と `catch` メソッドでも実現できますが、 `Promise#finally` メソッドを使うことで `isLoading` の代入を一箇所にまとめられます。
